import os
import time

from prometheus_client import CollectorRegistry, Gauge, push_to_gateway

from codeguardian.logging_utils import logger
from codeguardian.models import AnalysisMetrics, CommentSyncResult, ExecutionMetrics


PUSHGATEWAY_URL = os.getenv("PUSHGATEWAY_URL", "pushgateway:9091")


def metric_grouping_key(project_key: str, current_timestamp: float | None = None) -> dict[str, str]:
    return {
        "event_type": "pull_request",
        "repository": project_key,
    }


def _set_gauge(registry: CollectorRegistry, name: str, description: str, value: float) -> None:
    metric = Gauge(name, description, registry=registry)
    metric.set(value)


def build_metrics_registry(
    analysis: AnalysisMetrics,
    execution: ExecutionMetrics,
    comments: CommentSyncResult,
) -> CollectorRegistry:
    registry = CollectorRegistry()

    _set_gauge(
        registry,
        "codeguardian_analysis_latency_seconds",
        "Response time of Gemini model in seconds",
        analysis.latency_seconds,
    )
    _set_gauge(
        registry,
        "codeguardian_last_execution_timestamp",
        "Timestamp of the last agent execution",
        time.time(),
    )
    _set_gauge(
        registry,
        "codeguardian_analysis_prompt_tokens",
        "Tokens used in the prompt sent to Gemini model",
        analysis.prompt_tokens,
    )
    _set_gauge(
        registry,
        "codeguardian_analysis_response_tokens",
        "Tokens used in the response received from Gemini model",
        analysis.response_tokens,
    )
    _set_gauge(
        registry,
        "codeguardian_analysis_total_tokens",
        "Total tokens used in the Gemini model interaction",
        analysis.total_tokens,
    )
    _set_gauge(
        registry,
        "codeguardian_analysis_cached_tokens",
        "Cached tokens reported by Gemini",
        analysis.cached_tokens,
    )
    _set_gauge(
        registry,
        "codeguardian_batch_cache_hits_total",
        "Number of Gemini batch cache hits in the execution",
        analysis.batch_cache_hits,
    )
    _set_gauge(
        registry,
        "codeguardian_batch_cache_misses_total",
        "Number of Gemini batch cache misses in the execution",
        analysis.batch_cache_misses,
    )
    _set_gauge(
        registry,
        "codeguardian_performance_candidates_total",
        "Number of performance candidate scopes available before AI review",
        analysis.performance_candidates,
    )
    _set_gauge(
        registry,
        "codeguardian_performance_suggestions_total",
        "Number of optimization suggestions generated before validation",
        analysis.performance_suggestions,
    )
    _set_gauge(
        registry,
        "codeguardian_sonar_findings_total",
        "Number of relevant SonarQube findings read by the agent",
        execution.sonar_findings,
    )
    _set_gauge(
        registry,
        "codeguardian_generated_issues_total",
        "Number of issues generated by the AI model before validation",
        execution.generated_issues,
    )
    _set_gauge(
        registry,
        "codeguardian_invalid_issues_total",
        "Number of generated issues dropped during structural normalization",
        execution.invalid_issues,
    )
    _set_gauge(
        registry,
        "codeguardian_patch_invalid_issues_total",
        "Number of generated issues dropped during patch validation",
        execution.patch_invalid_issues,
    )
    _set_gauge(
        registry,
        "codeguardian_final_issues_total",
        "Number of final issues published or kept by the agent",
        execution.final_issues,
    )
    _set_gauge(
        registry,
        "codeguardian_blocking_findings",
        "Whether the execution had BLOCKER or CRITICAL SonarQube findings",
        1 if execution.blocking_findings else 0,
    )
    _set_gauge(
        registry,
        "codeguardian_comments_desired_total",
        "Number of desired Bitbucket inline comments after synchronization",
        comments.desired,
    )
    _set_gauge(
        registry,
        "codeguardian_comments_created_total",
        "Number of Bitbucket inline comments created by the agent",
        comments.created,
    )
    _set_gauge(
        registry,
        "codeguardian_comments_reused_total",
        "Number of existing Bitbucket inline comments reused by the agent",
        comments.reused,
    )
    _set_gauge(
        registry,
        "codeguardian_comments_deleted_total",
        "Number of obsolete Bitbucket inline comments deleted by the agent",
        comments.deleted,
    )
    _set_gauge(
        registry,
        "codeguardian_comments_resolved_total",
        "Number of obsolete Bitbucket inline comment threads resolved by the agent",
        comments.resolved,
    )
    _set_gauge(
        registry,
        "codeguardian_comments_kept_total",
        "Number of obsolete Bitbucket inline comments left untouched by the agent",
        comments.kept,
    )
    _set_gauge(
        registry,
        "codeguardian_comments_sync_failed_total",
        "Number of Bitbucket inline comments that could not be synchronized",
        comments.failed,
    )

    return registry


def push_execution_metrics(
    project_key: str,
    analysis: AnalysisMetrics,
    execution: ExecutionMetrics,
    comments: CommentSyncResult,
) -> None:
    registry = build_metrics_registry(analysis, execution, comments)

    try:
        push_to_gateway(
            PUSHGATEWAY_URL,
            job="codeguardian_agent",
            grouping_key=metric_grouping_key(project_key),
            registry=registry,
        )
        logger.info("Execution metrics pushed to Prometheus Pushgateway")
    except Exception as metric_error:
        logger.error("Failed to push metrics to Prometheus Pushgateway: %s", metric_error)
